Working through video 1 in "Joining Data with Pandas", the video uses Chicago dataportal data (wards) and census data for examples

In [1]:
import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofchicago.org", None)

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("htai-wnw4", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [4]:
results_df.columns

Index(['ward', 'alderman', 'address', 'city', 'state', 'zipcode', 'ward_phone',
       'ward_fax', 'email', 'website', 'location', 'city_hall_address',
       'city_hall_city', 'city_hall_state', 'city_hall_zipcode',
       'city_hall_phone', 'photo_link', ':@computed_region_rpca_8um6',
       ':@computed_region_vrxf_vc4k', ':@computed_region_6mkv_f3dw',
       ':@computed_region_bdys_3d7i', ':@computed_region_43wa_7qmu',
       ':@computed_region_awaf_s7ux'],
      dtype='object')

Note: Socrata -> government, NGO, non-profit datasets. Check the site for code snippets to import datasets

In [7]:
# For consistency with videos, turn that "results" dataset into "ward" with columns ward, alderman, address, zip
wards = results_df[['ward','alderman','address','zipcode']]

- Now, time to get the census data. Want ward, pop_2000, pop_2010, change, address, and zip (might need to look around for the right dataset?)
- Looks like that dataset isn't available, or at least I can't find it. I'll grab a different dataset where ward is one of the variables and work from there, since the point is to do an inner-join
- "ACS 5 Year Data by Ward" is interesting at least, so I'll grab that.

In [9]:
# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("awnk-6fvc", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

census = results_df[['ward','total_population']]

In [10]:
wards_census=wards.merge(census, on="ward")
wards_census.head(4)

,ward,alderman,address,zipcode,total_population
0,1,"La Spata, Daniel",1958 North Milwaukee Avenue,60647,56174.0
1,2,"Hopkins, Brian","121 North LaSalle Street, Room 300",60602,58472.0
2,3,"Dowell, Pat",5046 South State Street,60609,55444.0
3,4,"Robinson, Lamont J.",928 East 43rd Street,60653,51937.0

In [18]:
# Why do this? Ex. Sort merged dataset by total population, find the name of the Alderman with the most populous ward
wards_census.sort_values('total_population',ascending=False)[['alderman']].head(1)

           alderman
41  Reilly, Brendan

Inner Join
- Programmer speak for a kind of set intersection. Middle of the Venn-diagram.