# Experimenting with Joins

In [2]:
# Experimenting with one-to-one and one-to-many joins
import pandas as pd

# Make up two toy dataframes
data1 = {
    'A' : ['a1','a2'],
    'B' : ['b1','b2'],
}
data2 = {
    'B' : ['b1','b3'],
    'C' : ['c1','c2'],
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Now, in theory, if I merge these two, I *think* I should get something with only one row if I merge df2 onto df1
df1.merge(df2,on="B")

    A   B   C
0  a1  b1  c1

In [4]:
#Okay, that went as expected. Now, let's modify it and test a one-to-many join
# Make up two toy dataframes
data1 = {
    'A' : ['a1','a2'],
    'B' : ['b1','b2'],
}
data2 = {
    'B' : ['b1','b1', 'b2'],
    'C' : ['c1','c2', 'c3'],
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# If I merge these two now, I should get something with 3 rows... I think?
df1.merge(df2,on="B")

    A   B   C
0  a1  b1  c1
1  a1  b1  c2
2  a2  b2  c3