# Intro to other file types

- Will use Excel spreadsheets, MATLAB, SAS, Stata, and HDF5

## Pickled files (`.pkl`)

- Native to Python
- Serialized  (converted to bytestream)
- Importing is similar to importing raw text in Python
- import arg `'rb'` specifies 'read only' and 'binary'

import pickle
with open('pickled_fruit.pkl', 'rb') as file:
    data = pickle.load(file)
print(data)

## Excel spreadsheets
- Many ways, but can use `data = pd.ExcelFile(file)`
- Find the sheets using `data.sheet_names`
- Convert to a dataframe using `df = data.parse(sheet_name)` with sheet_name as a string or `df=data.parse(index)` with sheet index as a float
- `data.parse(sheet_name, usecols= , skiprows = , names = [])`
    - Use `skiprows` as usual, `names` to specify the names of the columns with a list (one per column), `usecols = ` to specify which columns to keep by index(?)

## Exploring the current working directory

- Use the `os` library -> `import os`
- Use `wd = os.getcwd()` to save the current working directory to the variable `wd`
- Use `os.listdir(wd)` to list the contents of the directory

In [1]:
import os
wd = os.getcwd()
os.listdir(wd)

['1. Intro and flat files.ipynb',
 '2. Introduction other file types.ipynb',
 'datasets']

# Importing SAS/Stata files using pandas

- SAS -> Commmon in business analytics and biostatistics
- Stata -> academic social sciences research (economics, epidemiology)

## Importing SAS files
- Most commonly have extension `.sas7bdat` or `.SAS7BDAT`
- sas7bdat library must installed locally (just like pandas or whatever)
- Use a context manager (ie. `with SAS7BDAT(location) as file:`)
- `from` lower_case `import` UPPER_CASE -> `from sas7bdat import SAS7BDAT`

In [3]:
import pandas as pd
from sas7bdat import SAS7BDAT
with SAS7BDAT('./datasets/sales.sas7bdat') as file:
    df_sas = file.to_data_frame()

df_sas.head()

     YEAR     P           S
0  1950.0  12.9  181.899994
1  1951.0  11.9  245.000000
2  1952.0  10.7  250.199997
3  1953.0  11.3  265.899994
4  1954.0  11.2  248.500000

## Importing Stata files

- No context manager needed
- Function built into pandas `pd.read_stata()`

In [4]:
import pandas as pd
data = pd.read_stata('datasets/disarea.dta')
data.head()

,wbcode,country,disa1,disa2,disa3,disa4,disa5,disa6,disa7,disa8,...,disa16,disa17,disa18,disa19,disa20,disa21,disa22,disa23,disa24,disa25
0,AFG,Afghanistan,0.00,0.00,0.76,0.73,0.0,0.00,0.00,0.0,...,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.02,0.00,0.00
1,AGO,Angola,0.32,0.02,0.56,0.00,0.0,0.00,0.56,0.0,...,0.0,0.4,0.0,0.61,0.00,0.0,0.99,0.98,0.61,0.00
2,ALB,Albania,0.00,0.00,0.02,0.00,0.0,0.00,0.00,0.0,...,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.16
3,ARE,United Arab Emirates,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,...,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00
4,ARG,Argentina,0.00,0.24,0.24,0.00,0.0,0.23,0.00,0.0,...,0.0,0.0,0.0,0.00,0.05,0.0,0.00,0.01,0.00,0.11

# Importing HDF5 files

- HDF5 -> Hierarchical Data Format version 5
- Standard for storing large quantities of numerical data
- Datasets can be hundreds of gigs or terabytes
- Could be up to *exabytes*

- Need `h5py` package!!!
    - Use `data = h5py.File(filename, 'r')` to read h5py into data variable ('r' is to read)

In [6]:
import h5py
data = h5py.File('datasets/L-L1_LOSC_4_V1-1126259446-32.hdf5', 'r')
print(type(data))

<class 'h5py._hl.files.File'>

## Structure of HDF5 files
- Explore like a dictionary using method `.keys()`

In [7]:
for key in data.keys():
    print(key)

meta
quality
strain

- Each `key` is a 'directory'
    - `meta` contains meta-data for the file
    - `quality` refers to data quality
    - `strain` refers to strain data from interferometer
- Find values of metadata like above

In [8]:
for key in data['meta'].keys():
    print(key)

Description
DescriptionURL
Detector
Duration
GPSstart
Observatory
Type
UTCstart

- Maybe we want the description and detector?
    - Convert values to numpy arrays -> `np.array(data['directory']['value'])`

In [9]:
import numpy as np
description, detector = np.array(data['meta']['Description']), np.array(data['meta']['Detector'])
print(description, detector)

np.bytes_(b'Strain data time series from LIGO') np.bytes_(b'L1')

In [10]:
print(np.array(data['meta']['Description']), np.array(data['meta']['Detector']))

np.bytes_(b'Strain data time series from LIGO') np.bytes_(b'L1')

- Note: Check out tutorial on LIGO data signal processing at https://gwosc.org/GW150914data/LOSC_Event_tutorial_GW150914.html
    - Check out ligo data at https://gwosc.org/events/GW150914/

# Importing MATLAB files

- `.mat` files
- Use standard `SciPy` library:
    - `scipy.io.loadmat()` - read
    - `scipy.io.savemat()` - write
- `.loadmat()` imports data as a dictionary
    - Keys are variable names
    - Values are objects assigned to variables

In [14]:
import scipy.io
filename = 'datasets/ja_data2.mat'
mat = scipy.io.loadmat(filename)
print(mat.keys())

dict_keys(['__header__', '__version__', '__globals__', 'rfpCyt', 'rfpNuc', 'cfpNuc', 'cfpCyt', 'yfpNuc', 'yfpCyt', 'CYratioCyt'])